# ========= APP / NEXT =========
AUTH_SECRET="defina-um-segredo-forte"
AUTH_GITHUB_ID=xxxxxxxxxxxxxxxx
AUTH_GITHUB_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AUTH_GOOGLE_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
AUTH_GOOGLE_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

NEXT_PUBLIC_URL=https://app.seu-dominio.com
NEXT_PUBLIC_APP_URL=https://app.seu-dominio.com
NEXT_PUBLIC_API_URL=https://api.seu-dominio.com

# ========= DATABASE (Supabase em produção) =========
DATABASE_URL="postgresql://<USER>:<PASS>@supabase.mondaha.com:6543/postgres?schema=public&pgbouncer=true&connection_limit=1"
DIRECT_URL="postgresql://<USER>:<PASS>@supabase.mondaha.com:5432/postgres?schema=public"

# ========= STRIPE (live ou test) =========
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_live_xxxxxxxxxxxxxxxxx
STRIPE_SECRET_KEY=sk_live_xxxxxxxxxxxxxxxxx
STRIPE_SECRET_WEBHOOK_KEY=whsec_xxxxxxxxxxxxxxxxx
STRIPE_PLAN_BASIC=price_live_xxxxxxxxx
STRIPE_PLAN_PROFISSIONAL=price_live_xxxxxxxxx
STRIPE_SUCCESS_URL=https://app.seu-dominio.com/dashboard/plans
STRIPE_CANCEL_URL=https://app.seu-dominio.com/dashboard/plans

# ========= STORAGE =========
CLOUDINARY_NAME=dht5d3hmg
CLOUDINARY_KEY=681918372266766
CLOUDINARY_SECRET=bP6bLPuVNAU4fBsSX7M0Fe4rwDQ

# ========= API (NestJS) =========
API_PORT=4000
API_CORS_ORIGIN=https://app.seu-dominio.com