apiVersion: 1

deleteDatasources:
- name: Prometheus
- name: Tempo

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  editable: true

- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  editable: true
  jsonData:
    httpMethod: GET
