name: Swagger Artifact

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - "prisma/**"
  workflow_dispatch:

jobs:
  openapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: api/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Prisma generate
        run: npx prisma generate --schema=../prisma/schema.prisma
      - name: Generate Swagger JSON (offline)
        env:
          OPENAPI_ONLY: "1"
          SKIP_PRISMA_CONNECT: "1"
          SKIP_METRICS: "1"
        run: npm run openapi:json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: swagger-json
          path: api/dist/swagger.json
          if-no-files-found: error
